name: Find merge conflicts

on:
  pull_request:
    types: [ synchronize ]
  push:
    branches:
      - "main"

env:
  
  MERGE_CONFLICT: "error | merge conflict"
  

jobs:
  check_pr_open_events:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          retries: 3
          github-token: ${{ secrets.ACTIONS_TOKEN }}
          script: |
            try {
              const pr = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: 1,
              });
            } catch (error) {
              console.error(error.message);
              return
            }

            if (pr.data.mergeable_state == "unknown") {
              core.setFailed('State is unknown, GitHub didn`t finish the checks');
              return;
            }

            console.log(pr.data.mergeable_state);
